config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  root to: 'tasks#home'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
  post '/tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def home
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to '/tasks'
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to '/tasks'
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to '/tasks'
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <% if @task.new_record? == false %>
    <%= f.label :completed %>
    <%= f.text_field :completed %>
  <% end %>
  <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>
<%= link_to "Back", :back %>

app/views/tasks/home.html.erb
<h1>Welcome to your to do list!</h1>
<h2>What would you like to do?</h2>
<ul>
  <li><%= link_to 'See my tasks', '/tasks' %></li>
  <li><%= link_to 'Create a new task', '/tasks/new' %></li>
  <li><%= link_to 'Update a task', '/tasks/new' %></li>
</ul>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
  <% @tasks.each_with_index do |task, index| %>
    <% if task.completed %>
    <li> <input type="checkbox" checked> <%= link_to task.title, task_path(task)%> <%= link_to delete_path(task), method: :delete, data: { confirm: "Delete #{task.title}?" } do %> <i class="fa fa-trash"></i><%end%></li>
    <% else %>
    <li> <input type="checkbox"> <%= link_to task.title, task_path(task)%> <%= link_to delete_path(task), method: :delete, data: { confirm: "Delete #{task.title}?" } do %> <i class="fa fa-trash"></i><%end%></li>
    <%end%>
  <% end %>
</ul>



<hr>

<%= link_to 'Add a new task', '/tasks/new' %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>
<%= link_to "Back", :back %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<% if @task.completed %>
  <input type="checkbox" checked>This task is completed!
<% else %>
  <input type="checkbox">This take isn't completed yet...
<%end%>
<hr>
<%= link_to 'Edit this task', edit_path(@task) %>
<br>
<%= link_to 'Homepage', '/tasks'  %>